import { patchEnvFile } from 'portta-core'
// `portta tls`: optional local HTTPS.
//
// HTTP works with no setup and is the right default for local development.
// Local HTTPS matters when you need a secure context: Secure cookies, service
// workers, WebAuthn, some SameSite behaviour.
//
// Certificate generation runs in the toolbox container, so the host needs no
// openssl. Trusting the CA does not: that writes to the operating system's
// trust store, so it stays a privileged action the operator performs
// deliberately, with the exact command printed. That is a security property,
// not an implementation detail — this command never runs `sudo`.

import { chmodSync, existsSync, mkdirSync, writeFileSync } from 'node:fs'
import { platform } from 'node:os'
import { join } from 'node:path'
import type { Command } from 'commander'
import { gatewayContext } from '../context.js'
import { requireDocker } from '../docker.js'
import { PreconditionError } from '../errors.js'
import { Output } from '../output.js'
import { runProcess } from '../process.js'
import { runInToolbox } from '../toolbox.js'

function globals(command: Command) { return command.optsWithGlobals() as { json?: boolean; yes?: boolean; quiet?: boolean; verbose?: boolean; profile?: string } }

/** Everything `tls` writes lives here, and the directory is git-ignored. */
export function tlsPaths(root: string) {
  const directory = join(root, 'config/tls')
  return {
    directory,
    caKey: join(directory, 'portta-ca.key'),
    caCertificate: join(directory, 'portta-ca.crt'),
    leafKey: join(directory, 'wildcard.key'),
    leafCertificate: join(directory, 'wildcard.crt'),
    dynamic: join(root, 'config/traefik/dynamic/local-tls.yaml'),
  }
}

/**
 * Traefik reads the certificate through the file provider. Regenerating it is
 * the only way to change it, which is why deleting this file is safe.
 */
export function localTlsDynamic(): string {
  return `# Generated by \`portta tls init\`. Safe to delete: re-run the command to
# recreate it. The certificate and key live in config/tls/, which is git-ignored.
tls:
  stores:
    default:
      defaultCertificate:
        certFile: /etc/traefik/tls/wildcard.crt
        keyFile: /etc/traefik/tls/wildcard.key
  certificates:
    - certFile: /etc/traefik/tls/wildcard.crt
      keyFile: /etc/traefik/tls/wildcard.key
`
}

/**
 * The names a certificate covers.
 *
 * `-ext subjectAltName` is missing from LibreSSL, which is what macOS ships as
 * `openssl`, so this parses `-text` instead: it works on both.
 */
export function parseSubjectAltNames(text: string): string[] {
  const lines = text.split('\n')
  const at = lines.findIndex((line) => line.includes('Subject Alternative Name'))
  if (at === -1) return []
  return [...(lines[at + 1] ?? '').matchAll(/DNS:([^,\s]+)/g)].map((match) => match[1]!)
}

/**
 * Read a certificate with the host's own `openssl` when it has one, and with
 * the toolbox otherwise. `status` is a read command people run often, and four
 * containers to print two dates is not a trade worth making on a host that can
 * answer directly.
 */
async function certificateFacts(root: string, path: string): Promise<{ expires: string | null; names: string[] }> {
  if (!existsSync(path)) return { expires: null, names: [] }

  const hostOpenssl = await runProcess('which', ['openssl'], { reject: false })
  const read = async (...flags: string[]) => hostOpenssl.failed || !hostOpenssl.stdout.trim()
    ? runInToolbox(root, ['openssl', 'x509', '-in', '/in/cert.pem', '-noout', ...flags], { volumes: [`${path}:/in/cert.pem:ro`] })
    : runProcess('openssl', ['x509', '-in', path, '-noout', ...flags], { reject: false })

  const end = await read('-enddate')
  const text = await read('-text')
  return {
    expires: end.failed ? null : end.stdout.trim().replace(/^notAfter=/, ''),
    names: text.failed ? [] : parseSubjectAltNames(text.stdout),
  }
}

export async function tlsStatus(command: Command): Promise<void> {
  const global = globals(command)
  const context = gatewayContext({ profile: global.profile })
  const paths = tlsPaths(context.root)
  const leaf = await certificateFacts(context.root, paths.leafCertificate)
  const authority = await certificateFacts(context.root, paths.caCertificate)

  const value = {
    enabled: context.config.tlsEnabled,
    mode: context.config.tlsMode,
    domain: context.config.domain,
    certificate: { present: existsSync(paths.leafCertificate), path: paths.leafCertificate, expires: leaf.expires, names: leaf.names },
    authority: { present: existsSync(paths.caCertificate), path: paths.caCertificate, expires: authority.expires },
    acme: context.config.tlsMode === 'acme'
      ? { emailSet: Boolean(context.env['ACME_EMAIL']), directory: context.env['ACME_CA_SERVER'], provider: context.env['ACME_DNS_PROVIDER'] }
      : null,
  }

  const output = new Output(global)
  if (output.json) { output.data(value); return }
  output.line(`enabled: ${value.enabled}`)
  output.line(`mode: ${value.mode}`)
  output.line(`domain: ${value.domain}`)
  if (value.acme) {
    output.line(`acme email: ${value.acme.emailSet ? 'set' : '<unset>'}`)
    output.line(`acme directory: ${value.acme.directory ?? ''}`)
    output.line(`dns provider: ${value.acme.provider ?? ''}`)
    return
  }
  output.line(`local CA: ${value.authority.present ? value.authority.path : 'not created'}`)
  if (!value.authority.present) output.hint('portta tls init')
  if (value.certificate.present) {
    output.line(`certificate: ${value.certificate.path}`)
    if (value.certificate.names.length) output.line(`covers: ${value.certificate.names.join(', ')}`)
    if (value.certificate.expires) output.line(`expires: ${value.certificate.expires}`)
  }
}

export async function tlsInit(command: Command): Promise<void> {
  const global = globals(command)
  const output = new Output(global)
  const context = gatewayContext({ profile: global.profile })
  await requireDocker()

  const paths = tlsPaths(context.root)
  const domain = context.config.domain
  mkdirSync(paths.directory, { recursive: true })
  chmodSync(paths.directory, 0o700)

  if (existsSync(paths.caKey)) {
    output.progress('reusing the existing local CA')
  } else {
    output.progress('creating a local certificate authority')
    // Generated inside the toolbox so the host needs no openssl. The private
    // key never leaves this directory.
    // chmod runs inside the container: on Linux the daemon writes into the bind
    // mount as root, so a host-side chmod by the invoking user would fail and
    // the CA key would be left world-readable.
    const created = await runInToolbox(context.root, ['sh', '-c', [
      'set -e',
      'openssl req -x509 -newkey rsa:4096 -sha256 -days 1825 -nodes'
        + ' -keyout /out/portta-ca.key -out /out/portta-ca.crt'
        + ' -subj "/CN=Portta local CA/O=Portta"'
        + ' -addext "basicConstraints=critical,CA:TRUE,pathlen:0"'
        + ' -addext "keyUsage=critical,keyCertSign,cRLSign"',
      'chmod 600 /out/portta-ca.key',
    ].join('\n')], { volumes: [`${paths.directory}:/out`] })
    if (created.failed) throw new PreconditionError('could not create the CA', created.stderr.trim() || 'see docs/dns-and-tls.md')
    output.progress(`created ${paths.caCertificate}`)
  }

  output.progress(`issuing a wildcard certificate for *.${domain}`)
  // Two openssl invocations sharing a working directory, so the CSR and the
  // extension file exist for the second one. The domain arrives as an
  // environment variable rather than interpolated into a command line.
  const issued = await runInToolbox(context.root, ['sh', '-c', [
    'set -e',
    'openssl req -newkey rsa:2048 -nodes -keyout /out/wildcard.key -out /tmp/wildcard.csr -subj "/CN=*.$DOMAIN"',
    'printf "subjectAltName=DNS:*.%s,DNS:%s\\nextendedKeyUsage=serverAuth\\nbasicConstraints=CA:FALSE\\n" "$DOMAIN" "$DOMAIN" > /tmp/ext',
    'openssl x509 -req -in /tmp/wildcard.csr -CA /out/portta-ca.crt -CAkey /out/portta-ca.key -CAcreateserial -out /out/wildcard.crt -days 397 -sha256 -extfile /tmp/ext',
    'chmod 600 /out/wildcard.key',
  ].join('\n')], { volumes: [`${paths.directory}:/out`], env: { DOMAIN: domain } })
  if (issued.failed) throw new PreconditionError('could not issue the certificate', issued.stderr.trim() || 'see docs/dns-and-tls.md')

  // Belt and braces for the host-openssl path, where nothing ran the chmod above.
  for (const key of [paths.caKey, paths.leafKey]) {
    try { chmodSync(key, 0o600) } catch { /* already owner-only, or owned by root: the directory is 700 either way */ }
  }
  output.progress(`issued ${paths.leafCertificate} for *.${domain}`)

  writeFileSync(paths.dynamic, localTlsDynamic())

  const envPath = join(context.root, '.env')
  patchEnvFile(envPath, { TLS_ENABLED: 'true', TLS_MODE: 'local' })
  output.progress('TLS enabled in .env')

  output.line('')
  printTrust(output, paths.caCertificate)
  output.hint(`then: portta up ${context.config.profile}`)
}

function printTrust(output: Output, certificate: string): void {
  output.line('Trusting the local CA')
  output.line('This writes to your operating system trust store, so the gateway will not do it for you. Run the command that matches your system:')
  output.line('')
  if (platform() === 'darwin') {
    output.line('  sudo security add-trusted-cert -d -r trustRoot \\')
    output.line(`    -k /Library/Keychains/System.keychain "${certificate}"`)
  } else if (platform() === 'linux') {
    output.line(`  sudo cp "${certificate}" /usr/local/share/ca-certificates/portta-ca.crt`)
    output.line('  sudo update-ca-certificates')
  } else {
    output.line(`  Import ${certificate} into your system trust store as a root certificate.`)
  }
  output.line('')
  output.line('Firefox keeps its own store: Settings -> Privacy & Security -> Certificates -> View Certificates -> Authorities -> Import.')
  output.line('Remove it later with: portta tls untrust')
}

export async function tlsTrust(command: Command): Promise<void> {
  const global = globals(command)
  const context = gatewayContext({ profile: global.profile })
  const paths = tlsPaths(context.root)
  if (!existsSync(paths.caCertificate)) throw new PreconditionError('no local CA yet', 'portta tls init')
  printTrust(new Output(global), paths.caCertificate)
}

export async function tlsUntrust(command: Command): Promise<void> {
  const global = globals(command)
  const context = gatewayContext({ profile: global.profile })
  const output = new Output(global)
  output.line('Removing the local CA from the trust store')
  if (platform() === 'darwin') {
    output.line('  sudo security delete-certificate -c "Portta local CA" \\')
    output.line('    /Library/Keychains/System.keychain')
  } else if (platform() === 'linux') {
    output.line('  sudo rm -f /usr/local/share/ca-certificates/portta-ca.crt')
    output.line('  sudo update-ca-certificates --fresh')
  } else {
    output.line('  Remove "Portta local CA" from your system trust store.')
  }
  output.line('')
  output.line(`To delete the key material as well: rm -rf ${paths(context.root)}`)
}

function paths(root: string): string {
  return join(root, 'config/tls')
}
