import { mkdtempSync, readFileSync, readdirSync, writeFileSync, statSync, existsSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { describe, expect, it } from 'vitest'
import { emptyProtectionStore, readProtectionStore, setProtection, writeProtectionStore } from 'portta-core'
import {
  DynamicWriteRefused,
  GENERATED_FILES,
  reconcilePanelDynamic,
  removeGenerated,
  writeGenerated,
} from '../src/services/dynamic.ts'
import { testConfig } from './helpers.ts'

function scratch(): string {
  return mkdtempSync(join(tmpdir(), 'portta-dynamic-'))
}

describe('the write allowlist', () => {
  it('writes the two files it owns', () => {
    const dir = scratch()
    writeGenerated(dir, GENERATED_FILES.panel, 'http: {}\n')
    writeGenerated(dir, GENERATED_FILES.shares, 'http: {}\n')
    expect(existsSync(join(dir, GENERATED_FILES.panel))).toBe(true)
    expect(existsSync(join(dir, GENERATED_FILES.shares))).toBe(true)
  })

  it('refuses every other file in the directory', () => {
    const dir = scratch()
    // These are the user's, and Traefik reads them.
    for (const name of ['middlewares.yaml', 'tcp.yaml', 'local-tls.yaml', 'auth.yaml']) {
      expect(() => writeGenerated(dir, name, 'http: {}\n')).toThrow(DynamicWriteRefused)
    }
  })

  it('refuses a path that tries to leave the directory', () => {
    const dir = scratch()
    for (const name of ['../compose.yaml', '../../.env', '/etc/passwd', 'sub/portta-panel.yaml']) {
      expect(() => writeGenerated(dir, name, 'x')).toThrow(DynamicWriteRefused)
    }
  })

  it('refuses to delete a file it does not own', () => {
    const dir = scratch()
    writeFileSync(join(dir, 'middlewares.yaml'), 'http: {}\n')
    expect(() => removeGenerated(dir, 'middlewares.yaml')).toThrow(DynamicWriteRefused)
    expect(existsSync(join(dir, 'middlewares.yaml'))).toBe(true)
  })

  it('writes 600, because these files carry a password hash', () => {
    const dir = scratch()
    writeGenerated(dir, GENERATED_FILES.panel, 'http: {}\n')
    expect(statSync(join(dir, GENERATED_FILES.panel)).mode & 0o777).toBe(0o600)
  })

  it('leaves no temporary file behind for Traefik to read', () => {
    const dir = scratch()
    writeGenerated(dir, GENERATED_FILES.panel, 'http: {}\n')
    expect(readdirSync(dir)).toEqual([GENERATED_FILES.panel])
  })
})

describe('reconcilePanelDynamic', () => {
  function panelConfig(dir: string) {
    return testConfig({
      dynamicDir: dir,
      authStore: join(dir, 'auth/protections.json'),
      webExpose: 'vpn',
      domain: 'dev.example.com',
      tlsEnabled: true,
    })
  }

  it("leaves the panel's own file declaring nothing at all", () => {
    const dir = scratch()
    expect(reconcilePanelDynamic(panelConfig(dir)).written).toBe(true)
    const yaml = readFileSync(join(dir, GENERATED_FILES.panel), 'utf8')
    // `http: {}` is not an empty configuration to Traefik, it is an invalid
    // one, and one invalid file aborts every other file in the directory.
    expect(yaml).not.toMatch(/^http:/m)
    expect(yaml.split('\n').filter((line) => line !== '').every((line) => line.startsWith('#'))).toBe(true)
    expect(yaml).toContain('Generated by Portta panel')
  })

  it('still renders ForwardAuth, which projects and shares need', () => {
    const dir = scratch()
    const config = panelConfig(dir)
    writeProtectionStore(config.authStore, setProtection(emptyProtectionStore(), {
      scope: 'share:demo-web', host: 'demo-web.dev.example.com', entryPoints: ['websecure'],
      user: 'share', hash: '$apr1$a$b', label: 'demo-web',
    }))
    reconcilePanelDynamic(config)
    const yaml = readFileSync(join(dir, GENERATED_FILES.auth), 'utf8')
    expect(yaml).toContain('portta-forward-auth:')
    expect(yaml).toContain('demo-web.dev.example.com')
    expect(yaml).not.toContain('$apr1$')
  })

  // An upgraded host carries a store written by a Portta that put the panel
  // behind Traefik. Leaving those records would keep a middleware in front of a
  // panel that now decides for itself, and the two answers would disagree.
  it('removes the panel and dashboard records an older Portta left', () => {
    const dir = scratch()
    const config = panelConfig(dir)
    let store = setProtection(emptyProtectionStore(), {
      scope: 'panel', host: 'portta-web.dev.example.com', entryPoints: ['websecure'],
      user: 'dev', hash: '$apr1$a$b', label: 'Portta panel',
    })
    store = setProtection(store, {
      scope: 'dashboard', host: 'dev.example.com', entryPoints: ['websecure'],
      user: 'dev', hash: '$apr1$a$b', label: 'Traefik dashboard',
    })
    writeProtectionStore(config.authStore, store)

    expect(reconcilePanelDynamic(config).written).toBe(true)
    expect(readProtectionStore(config.authStore).protections).toEqual([])
    expect(readFileSync(join(dir, GENERATED_FILES.auth), 'utf8')).not.toContain('portta-web.dev.example.com')
  })

  it('does not rewrite what is already in step', () => {
    const dir = scratch()
    const config = panelConfig(dir)
    reconcilePanelDynamic(config)
    expect(reconcilePanelDynamic(config)).toMatchObject({ written: false, reason: 'already in step' })
  })

  it('reports rather than throws when the directory cannot be written', () => {
    // The parent is a regular file, so this can never be created — ENOTDIR for
    // every user, root included. A procfs path looks equivalent and is not: on
    // Linux a recursive mkdir there never returns. Same fix as
    // overrides.test.ts.
    const unwritable = join(scratch(), 'not-a-directory')
    writeFileSync(unwritable, '')
    const config = testConfig({ dynamicDir: join(unwritable, 'nowhere'), authStore: join(scratch(), 'auth/protections.json') })
    expect(reconcilePanelDynamic(config).written).toBe(false)
  })
})
